In [132]:
import pandas as pd 
import numpy as np

In [133]:
df=pd.read_csv("housing.csv")

In [134]:
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [135]:
df["income_cat"] = pd.cut(df["median_income"],bins=[0, 1.5, 3.0, 4.5, 6.0, np.inf],labels=[1, 2, 3, 4, 5])

In [136]:
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  \
0       322.0       126.0         8.3252            452600.0        NEAR BAY   
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY   
2       496.0       177.0         7.2574            352100.0        NEAR BAY   
3       558.0       219.0         5.6431            341300.0        NEAR BAY   
4       565.0       259.0         3.8462            342200.0        NEAR BAY   

  income_cat  
0          5  
1          5  
2          5  
3          4  
4          3

In [137]:
from sklearn.model_selection import StratifiedShuffleSplit

In [138]:
split = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
 # n_splits shows that how many splits we want...


In [139]:
split.split(df, df["income_cat"])

<generator object BaseShuffleSplit.split at 0x000002B0E47E6740>

In [140]:
for train_index, test_index in split.split(df, df["income_cat"]):
    strat_train_set = df.loc[train_index]
    strat_test_set = df.loc[test_index]

In [141]:
strat_train_set.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
12655    -121.46     38.52                29.0       3873.0           797.0   
15502    -117.23     33.09                 7.0       5320.0           855.0   
2908     -119.04     35.37                44.0       1618.0           310.0   
14053    -117.13     32.75                24.0       1877.0           519.0   
20496    -118.70     34.28                27.0       3536.0           646.0   

       population  households  median_income  median_house_value  \
12655      2237.0       706.0         2.1736             72100.0   
15502      2015.0       768.0         6.3373            279600.0   
2908        667.0       300.0         2.8750             82700.0   
14053       898.0       483.0         2.2264            112500.0   
20496      1837.0       580.0         4.4964            238300.0   

      ocean_proximity income_cat  
12655          INLAND          2  
15502      NEAR OCEAN          5  
2908           INLAND          2  
14053      NEAR OCEAN          2  
20496       <1H OCEAN          3

In [142]:
df=strat_train_set.copy()

In [143]:
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
12655    -121.46     38.52                29.0       3873.0           797.0   
15502    -117.23     33.09                 7.0       5320.0           855.0   
2908     -119.04     35.37                44.0       1618.0           310.0   
14053    -117.13     32.75                24.0       1877.0           519.0   
20496    -118.70     34.28                27.0       3536.0           646.0   
...          ...       ...                 ...          ...             ...   
15174    -117.07     33.03                14.0       6665.0          1231.0   
12661    -121.42     38.51                15.0       7901.0          1422.0   
19263    -122.72     38.44                48.0        707.0           166.0   
19140    -122.70     38.31                14.0       3155.0           580.0   
19773    -122.14     39.97                27.0       1079.0           222.0   

       population  households  median_income  median_house_value  \
12655      2237.0       706.0         2.1736             72100.0   
15502      2015.0       768.0         6.3373            279600.0   
2908        667.0       300.0         2.8750             82700.0   
14053       898.0       483.0         2.2264            112500.0   
20496      1837.0       580.0         4.4964            238300.0   
...           ...         ...            ...                 ...   
15174      2026.0      1001.0         5.0900            268500.0   
12661      4769.0      1418.0         2.8139             90400.0   
19263       458.0       172.0         3.1797            140400.0   
19140      1208.0       501.0         4.1964            258100.0   
19773       625.0       197.0         3.1319             62700.0   

      ocean_proximity income_cat  
12655          INLAND          2  
15502      NEAR OCEAN          5  
2908           INLAND          2  
14053      NEAR OCEAN          2  
20496       <1H OCEAN          3  
...               ...        ...  
15174       <1H OCEAN          4  
12661          INLAND          2  
19263       <1H OCEAN          3  
19140       <1H OCEAN          3  
19773          INLAND          3  

[16512 rows x 11 columns]

# for numerical columns

#### seperating features and labels

In [144]:
#here we are working with {strat_train_set) dataframe

housing_features= strat_train_set.drop("median_house_value",axis=1)
# why we can not use this--> housing_features= strat_train_set.drop("median_house_value",inplace=true)

housing_labels= strat_train_set["median_house_value"].copy()

In [145]:
housing_features

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
12655    -121.46     38.52                29.0       3873.0           797.0   
15502    -117.23     33.09                 7.0       5320.0           855.0   
2908     -119.04     35.37                44.0       1618.0           310.0   
14053    -117.13     32.75                24.0       1877.0           519.0   
20496    -118.70     34.28                27.0       3536.0           646.0   
...          ...       ...                 ...          ...             ...   
15174    -117.07     33.03                14.0       6665.0          1231.0   
12661    -121.42     38.51                15.0       7901.0          1422.0   
19263    -122.72     38.44                48.0        707.0           166.0   
19140    -122.70     38.31                14.0       3155.0           580.0   
19773    -122.14     39.97                27.0       1079.0           222.0   

       population  households  median_income ocean_proximity income_cat  
12655      2237.0       706.0         2.1736          INLAND          2  
15502      2015.0       768.0         6.3373      NEAR OCEAN          5  
2908        667.0       300.0         2.8750          INLAND          2  
14053       898.0       483.0         2.2264      NEAR OCEAN          2  
20496      1837.0       580.0         4.4964       <1H OCEAN          3  
...           ...         ...            ...             ...        ...  
15174      2026.0      1001.0         5.0900       <1H OCEAN          4  
12661      4769.0      1418.0         2.8139          INLAND          2  
19263       458.0       172.0         3.1797       <1H OCEAN          3  
19140      1208.0       501.0         4.1964       <1H OCEAN          3  
19773       625.0       197.0         3.1319          INLAND          3  

[16512 rows x 10 columns]

In [146]:
housing_labels

12655     72100.0
15502    279600.0
2908      82700.0
14053    112500.0
20496    238300.0
           ...   
15174    268500.0
12661     90400.0
19263    140400.0
19140    258100.0
19773     62700.0
Name: median_house_value, Length: 16512, dtype: float64

## Impute missing value

In [147]:
from sklearn.impute import SimpleImputer

In [148]:
imputer = SimpleImputer(strategy="median")

In [149]:
housing_num=housing_features.select_dtypes(include=[np.number])  # here we select only numerical columns {we remove 'ocean_proximity' columns}

In [150]:
imputer.fit(housing_num)

SimpleImputer(strategy='median')

In [151]:
imputer.statistics_


array([-118.51   ,   34.26   ,   29.     , 2119.     ,  433.     ,
       1164.     ,  408.     ,    3.54155])

In [152]:
X = imputer.transform(housing_num)

In [153]:
X

array([[-1.2146e+02,  3.8520e+01,  2.9000e+01, ...,  2.2370e+03,
         7.0600e+02,  2.1736e+00],
       [-1.1723e+02,  3.3090e+01,  7.0000e+00, ...,  2.0150e+03,
         7.6800e+02,  6.3373e+00],
       [-1.1904e+02,  3.5370e+01,  4.4000e+01, ...,  6.6700e+02,
         3.0000e+02,  2.8750e+00],
       ...,
       [-1.2272e+02,  3.8440e+01,  4.8000e+01, ...,  4.5800e+02,
         1.7200e+02,  3.1797e+00],
       [-1.2270e+02,  3.8310e+01,  1.4000e+01, ...,  1.2080e+03,
         5.0100e+02,  4.1964e+00],
       [-1.2214e+02,  3.9970e+01,  2.7000e+01, ...,  6.2500e+02,
         1.9700e+02,  3.1319e+00]])

# for categorical columns

In [154]:
housing=pd.DataFrame(X,columns=housing_num.columns,index=housing_num.index)

In [155]:
housing['ocean_proximity']=df['ocean_proximity']

In [156]:
housing

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
12655    -121.46     38.52                29.0       3873.0           797.0   
15502    -117.23     33.09                 7.0       5320.0           855.0   
2908     -119.04     35.37                44.0       1618.0           310.0   
14053    -117.13     32.75                24.0       1877.0           519.0   
20496    -118.70     34.28                27.0       3536.0           646.0   
...          ...       ...                 ...          ...             ...   
15174    -117.07     33.03                14.0       6665.0          1231.0   
12661    -121.42     38.51                15.0       7901.0          1422.0   
19263    -122.72     38.44                48.0        707.0           166.0   
19140    -122.70     38.31                14.0       3155.0           580.0   
19773    -122.14     39.97                27.0       1079.0           222.0   

       population  households  median_income ocean_proximity  
12655      2237.0       706.0         2.1736          INLAND  
15502      2015.0       768.0         6.3373      NEAR OCEAN  
2908        667.0       300.0         2.8750          INLAND  
14053       898.0       483.0         2.2264      NEAR OCEAN  
20496      1837.0       580.0         4.4964       <1H OCEAN  
...           ...         ...            ...             ...  
15174      2026.0      1001.0         5.0900       <1H OCEAN  
12661      4769.0      1418.0         2.8139          INLAND  
19263       458.0       172.0         3.1797       <1H OCEAN  
19140      1208.0       501.0         4.1964       <1H OCEAN  
19773       625.0       197.0         3.1319          INLAND  

[16512 rows x 9 columns]

In [157]:
housing=housing[['ocean_proximity']]

#### ordinal encoding

In [158]:
from sklearn.preprocessing import OrdinalEncoder

In [159]:
ordinal_encoder = OrdinalEncoder()


In [160]:
housing_cat=ordinal_encoder.fit_transform(housing)

In [161]:
housing_cat=pd.DataFrame(housing_cat,columns=housing.columns,index=housing.index)

In [162]:
housing_cat

ocean_proximity
12655              1.0
15502              4.0
2908               1.0
14053              4.0
20496              0.0
...                ...
15174              0.0
12661              1.0
19263              0.0
19140              0.0
19773              1.0

[16512 rows x 1 columns]

In [163]:
# ⚠️ Caution: Ordinal encoding implies an order between categories, 
# which may not be true here. For example, 
# it treats INLAND (1) as closer to <1H OCEAN (0) than NEAR OCEAN (4), which might not make sense.

#### One-Hot Encoding

In [164]:
from sklearn.preprocessing import OneHotEncoder

In [165]:
ordinal_encoder = OneHotEncoder()

In [166]:
housing_cat=ordinal_encoder.fit_transform(housing)

In [167]:
ordinal_encoder.categories_

[array(['<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'],
       dtype=object)]

In [168]:
housing_cat  # it return sparx matrix....


<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 16512 stored elements and shape (16512, 5)>

In [169]:
housing_cat.toarray()

array([[0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       ...,
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [170]:
housing_cat=pd.DataFrame(housing_cat.toarray(),columns=['<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'],index=housing.index)

In [171]:
housing_cat

<1H OCEAN  INLAND  ISLAND  NEAR BAY  NEAR OCEAN
12655        0.0     1.0     0.0       0.0         0.0
15502        0.0     0.0     0.0       0.0         1.0
2908         0.0     1.0     0.0       0.0         0.0
14053        0.0     0.0     0.0       0.0         1.0
20496        1.0     0.0     0.0       0.0         0.0
...          ...     ...     ...       ...         ...
15174        1.0     0.0     0.0       0.0         0.0
12661        0.0     1.0     0.0       0.0         0.0
19263        1.0     0.0     0.0       0.0         0.0
19140        1.0     0.0     0.0       0.0         0.0
19773        0.0     1.0     0.0       0.0         0.0

[16512 rows x 5 columns]

In [172]:
df=pd.concat([df,housing_cat],axis=1)

In [173]:
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
12655    -121.46     38.52                29.0       3873.0           797.0   
15502    -117.23     33.09                 7.0       5320.0           855.0   
2908     -119.04     35.37                44.0       1618.0           310.0   
14053    -117.13     32.75                24.0       1877.0           519.0   
20496    -118.70     34.28                27.0       3536.0           646.0   
...          ...       ...                 ...          ...             ...   
15174    -117.07     33.03                14.0       6665.0          1231.0   
12661    -121.42     38.51                15.0       7901.0          1422.0   
19263    -122.72     38.44                48.0        707.0           166.0   
19140    -122.70     38.31                14.0       3155.0           580.0   
19773    -122.14     39.97                27.0       1079.0           222.0   

       population  households  median_income  median_house_value  \
12655      2237.0       706.0         2.1736             72100.0   
15502      2015.0       768.0         6.3373            279600.0   
2908        667.0       300.0         2.8750             82700.0   
14053       898.0       483.0         2.2264            112500.0   
20496      1837.0       580.0         4.4964            238300.0   
...           ...         ...            ...                 ...   
15174      2026.0      1001.0         5.0900            268500.0   
12661      4769.0      1418.0         2.8139             90400.0   
19263       458.0       172.0         3.1797            140400.0   
19140      1208.0       501.0         4.1964            258100.0   
19773       625.0       197.0         3.1319             62700.0   

      ocean_proximity income_cat  <1H OCEAN  INLAND  ISLAND  NEAR BAY  \
12655          INLAND          2        0.0     1.0     0.0       0.0   
15502      NEAR OCEAN          5        0.0     0.0     0.0       0.0   
2908           INLAND          2        0.0     1.0     0.0       0.0   
14053      NEAR OCEAN          2        0.0     0.0     0.0       0.0   
20496       <1H OCEAN          3        1.0     0.0     0.0       0.0   
...               ...        ...        ...     ...     ...       ...   
15174       <1H OCEAN          4        1.0     0.0     0.0       0.0   
12661          INLAND          2        0.0     1.0     0.0       0.0   
19263       <1H OCEAN          3        1.0     0.0     0.0       0.0   
19140       <1H OCEAN          3        1.0     0.0     0.0       0.0   
19773          INLAND          3        0.0     1.0     0.0       0.0   

       NEAR OCEAN  
12655         0.0  
15502         1.0  
2908          0.0  
14053         1.0  
20496         0.0  
...           ...  
15174         0.0  
12661         0.0  
19263         0.0  
19140         0.0  
19773         0.0  

[16512 rows x 16 columns]

In [178]:
df=df.drop("ocean_proximity",axis=1)

## feature scaling

#### min max scaling(normalization)

In [179]:
from sklearn.preprocessing import MinMaxScaler

In [180]:
min_max_scaler=MinMaxScaler(feature_range=(-1,1))

In [181]:
df_scaled=min_max_scaler.fit_transform(df)

In [190]:
df_scaled # here it is numpy array, so we convert it into dataframe...

array([[-0.94135046,  1.34743822,  0.02756357, ..., -0.0110063 ,
        -0.3548889 , -0.38421741],
       [ 1.17178212, -1.19243966, -1.72201763, ..., -0.0110063 ,
        -0.3548889 ,  2.60269309],
       [ 0.26758118, -0.1259716 ,  1.22045984, ..., -0.0110063 ,
        -0.3548889 , -0.38421741],
       ...,
       [-1.5707942 ,  1.31001828,  1.53856552, ..., -0.0110063 ,
        -0.3548889 , -0.38421741],
       [-1.56080303,  1.2492109 , -1.1653327 , ..., -0.0110063 ,
        -0.3548889 , -0.38421741],
       [-1.28105026,  2.02567448, -0.13148926, ..., -0.0110063 ,
        -0.3548889 , -0.38421741]])

In [182]:
df_scaled=pd.DataFrame(df_scaled,columns=df.columns,index=df.index)

In [183]:
df_scaled

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
12655  -0.424303  0.270988            0.098039    -0.803276       -0.743879   
15502   0.418327 -0.883103           -0.764706    -0.729664       -0.725193   
2908    0.057769 -0.398512            0.686275    -0.917994       -0.900773   
14053   0.438247 -0.955367           -0.098039    -0.904818       -0.833441   
20496   0.125498 -0.630181            0.019608    -0.820420       -0.792526   
...          ...       ...                 ...          ...             ...   
15174   0.450199 -0.895855           -0.490196    -0.661240       -0.604059   
12661  -0.416335  0.268863           -0.450980    -0.598362       -0.542526   
19263  -0.675299  0.253985            0.843137    -0.964338       -0.947165   
19140  -0.671315  0.226355           -0.490196    -0.839803       -0.813789   
19773  -0.559761  0.579171            0.019608    -0.945414       -0.929124   

       population  households  median_income  median_house_value  income_cat  \
12655   -0.874772   -0.737117      -0.769148           -0.764533        -0.5   
15502   -0.887217   -0.713966      -0.194852            0.091134         1.0   
2908    -0.962779   -0.888723      -0.672405           -0.720822        -0.5   
14053   -0.949830   -0.820388      -0.761865           -0.597936        -0.5   
20496   -0.897194   -0.784167      -0.448766           -0.079175         0.0   
...           ...         ...            ...                 ...         ...   
15174   -0.886600   -0.626960      -0.366891            0.045361         0.5   
12661   -0.732840   -0.471247      -0.680832           -0.689069        -0.5   
19263   -0.974495   -0.936520      -0.630378           -0.482885         0.0   
19140   -0.932453   -0.813667      -0.490145            0.002474         0.0   
19773   -0.965134   -0.927184      -0.636971           -0.803296         0.0   

       <1H OCEAN  INLAND  ISLAND  NEAR BAY  NEAR OCEAN  
12655       -1.0     1.0    -1.0      -1.0        -1.0  
15502       -1.0    -1.0    -1.0      -1.0         1.0  
2908        -1.0     1.0    -1.0      -1.0        -1.0  
14053       -1.0    -1.0    -1.0      -1.0         1.0  
20496        1.0    -1.0    -1.0      -1.0        -1.0  
...          ...     ...     ...       ...         ...  
15174        1.0    -1.0    -1.0      -1.0        -1.0  
12661       -1.0     1.0    -1.0      -1.0        -1.0  
19263        1.0    -1.0    -1.0      -1.0        -1.0  
19140        1.0    -1.0    -1.0      -1.0        -1.0  
19773       -1.0     1.0    -1.0      -1.0        -1.0  

[16512 rows x 15 columns]

#### Z-score scaling(standardization)

In [184]:
from sklearn.preprocessing import StandardScaler

In [185]:
scaler=StandardScaler()

In [188]:
df_scaled=scaler.fit_transform(df)

In [189]:
df_scaled #here it is numpy arry , so we convert it into dataframe..

array([[-0.94135046,  1.34743822,  0.02756357, ..., -0.0110063 ,
        -0.3548889 , -0.38421741],
       [ 1.17178212, -1.19243966, -1.72201763, ..., -0.0110063 ,
        -0.3548889 ,  2.60269309],
       [ 0.26758118, -0.1259716 ,  1.22045984, ..., -0.0110063 ,
        -0.3548889 , -0.38421741],
       ...,
       [-1.5707942 ,  1.31001828,  1.53856552, ..., -0.0110063 ,
        -0.3548889 , -0.38421741],
       [-1.56080303,  1.2492109 , -1.1653327 , ..., -0.0110063 ,
        -0.3548889 , -0.38421741],
       [-1.28105026,  2.02567448, -0.13148926, ..., -0.0110063 ,
        -0.3548889 , -0.38421741]])

In [191]:
df_scaled=pd.DataFrame(df_scaled,columns=df.columns,index=df.index)

In [192]:
df_scaled

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
12655  -0.941350  1.347438            0.027564     0.584777        0.635123   
15502   1.171782 -1.192440           -1.722018     1.261467        0.775677   
2908    0.267581 -0.125972            1.220460    -0.469773       -0.545045   
14053   1.221738 -1.351474           -0.370069    -0.348652       -0.038567   
20496   0.437431 -0.635818           -0.131489     0.427179        0.269198   
...          ...       ...                 ...          ...             ...   
15174   1.251711 -1.220505           -1.165333     1.890456        1.686854   
12661  -0.921368  1.342761           -1.085806     2.468471        2.149712   
19263  -1.570794  1.310018            1.538566    -0.895802       -0.894007   
19140  -1.560803  1.249211           -1.165333     0.249005        0.109257   
19773  -1.281050  2.025674           -0.131489    -0.721836       -0.758300   

       population  households  median_income  median_house_value  income_cat  \
12655    0.732602    0.556286      -0.893647           -1.166015   -0.954687   
15502    0.533612    0.721318       1.292168            0.627451    1.890078   
2908    -0.674675   -0.524407      -0.525434           -1.074397   -0.954687   
14053   -0.467617   -0.037297      -0.865929           -0.816829   -0.954687   
20496    0.374060    0.220898       0.325752            0.270486   -0.006432   
...           ...         ...            ...                 ...         ...   
15174    0.543471    1.341519       0.637374            0.531511    0.941823   
12661    3.002174    2.451492      -0.557509           -1.007844   -0.954687   
19263   -0.862013   -0.865118      -0.365475           -0.575684   -0.006432   
19140   -0.189747    0.010616       0.168261            0.441622   -0.006432   
19773   -0.712322   -0.798573      -0.390569           -1.247261   -0.006432   

       <1H OCEAN   INLAND    ISLAND  NEAR BAY  NEAR OCEAN  
12655  -0.887683  1.46218 -0.011006 -0.354889   -0.384217  
15502  -0.887683 -0.68391 -0.011006 -0.354889    2.602693  
2908   -0.887683  1.46218 -0.011006 -0.354889   -0.384217  
14053  -0.887683 -0.68391 -0.011006 -0.354889    2.602693  
20496   1.126529 -0.68391 -0.011006 -0.354889   -0.384217  
...          ...      ...       ...       ...         ...  
15174   1.126529 -0.68391 -0.011006 -0.354889   -0.384217  
12661  -0.887683  1.46218 -0.011006 -0.354889   -0.384217  
19263   1.126529 -0.68391 -0.011006 -0.354889   -0.384217  
19140   1.126529 -0.68391 -0.011006 -0.354889   -0.384217  
19773  -0.887683  1.46218 -0.011006 -0.354889   -0.384217  

[16512 rows x 15 columns]